### ISSUE TITLE
Scale Issue

### ISSUE THREAD

**Issue by rmccawl** [gummesson/gulp-pixrem#2]
Hi there, 

I've just installed the plugin and it works great however, the converted pixel values are much higher than the original rem values. Is there a way to set the conversion calculation?

Example

```
body,html {font-size: 62.5%; }

// h1 styles
h1 {
font-family: 'Gotham A', 'Gotham B', 'Helvetica', 'Helvetica Neue', 'Arial', Sans-serif;
font-weight: 500;
font-style: normal;
font-size: 35px; // <--- This should be 22px 
font-size: 2.2rem;
line-height: 38px;
line-height: 2.4rem;
margin-bottom: 40px;
margin-bottom: 2.5rem;
}
```

When I set the pixels to 22px the text is the same size as it's orginal rem value.
See - http://snook.ca/archives/html_and_css/font-size-with-rem

**Comment by gummesson** [comment]
I was using an older version of `pixrem` that didn't get the root size from the CSS. I've now updated the version so it should work. Let me know if there's any problems!

**Comment by lambert-velir** [comment]
Cool, I've [updated](https://github.com/lambert-velir/gulp-pixrem-test/commit/ace0abd95ab8b0e994398c5d47428b2095a1d41d) gulp-pixrem from 0.1.1 to 0.1.2, and now it's working as expected.

```css
html {
    font-size: 12px;
}

body {
    font-size: 11px;
}

h1 {
    font-size: 24px;
    font-size: 2rem;
}
```

**Comment by gummesson** [comment]
Good! :+1:

**Comment by vladimirsiljkovic** [comment]
Hi Ellen,

Seems like this is broken again in the latest version of gulp-pixrem (0.2.0).

You can use the same test case from above to test (https://github.com/lambert-velir/gulp-pixrem-test), just change gulp-pixrem version from 0.1.2 to 0.2.0.

Version  0.1.2 worked fine with or without the default root value hard-coded in gulp, the value got overridden or set according to values from CSS file. Version 0.2.0 doesn't work either way, it uses value from gulpfile and ignores values from CSS file.

I've tested the latest version of node-pixrem (without Gulp) and it is working fine.

**Comment by gummesson** [comment]
@vladimirsiljkovic, I just published a new version that seems to fix it. Let me know if it works!

**Comment by vladimirsiljkovic** [comment]
It does work, thanks a lot!

However, now with this fix the default options (for `atrules`, `replace`, and `html`)  cannot be overridden. 

I tried both `.pipe(pixrem({ atrules: true }))` and `.pipe(pixrem('20px', { atrules: true }))` and neither seem to work.

**Comment by gummesson** [comment]
I forgot to switch the order of some parameters. It should be fixed now. Sorry!

**Comment by vladimirsiljkovic** [comment]
Just to confirm that everything is working now if options are passed as a second param (e.g. `.pipe(pixrem('20px', { atrules: true }))`), but defaults still can't be overridden if options are passed as the first param (e.g. `.pipe(pixrem({ atrules: true }))`).

I'm not quite sure a plugin should work with options passed as the first param (and based on the readme file – I think it should, as there is an example with `.pipe(pixrem({ replace: true }))`) but I'm happy with the way it works now, because the defaults root value from gulpfile will be overridden with the value from CSS anyway.

And thank you very much for the plugin, it's great!

**Comment by gummesson** [comment]
I think that's actually a `pixrem` issue since the library itself should probably check the `root` parameter... I'll update the README though. :)

And thank you for the troubleshooting!
